"""Public compatibility API for LINZA."""

from .compat import (
    __version__,
    LINZA_SCHEMA_VERSION,
    Storage,
    LinzaStorage,
    MeanCenteredEmbeddings,
    HashingEmbeddingProvider,
    LinzaCore,
    chunk_markdown,
    guess_note_role,
    material_type_vocabulary,
    extract_events,
    strip_frontmatter,
    cosine_similarity,
    content_hash,
    patch_frontmatter,
    format_yaml_block,
    is_legacy_graph_metadata,
    parse_frontmatter,
    extract_tags,
    extract_wikilinks,
    normalize_tag,
    extract_tag_details,
    LINZA_EVENT_PATTERNS,
    FRONTMATTER_RE,
    WIKILINK_RE,
    IGNORED_DIRS,
)
from .workflows import agent_workspace

__all__ = [
    "__version__",
    "LINZA_SCHEMA_VERSION",
    "Storage",
    "LinzaStorage",
    "MeanCenteredEmbeddings",
    "HashingEmbeddingProvider",
    "LinzaCore",
    "chunk_markdown",
    "guess_note_role",
    "material_type_vocabulary",
    "extract_events",
    "strip_frontmatter",
    "cosine_similarity",
    "content_hash",
    "agent_workspace",
    "patch_frontmatter",
    "format_yaml_block",
    "is_legacy_graph_metadata",
    "parse_frontmatter",
    "extract_wikilinks",
    "normalize_tag",
    "extract_tag_details",
    "extract_tags",
    "LINZA_EVENT_PATTERNS",
    "FRONTMATTER_RE",
    "WIKILINK_RE",
    "IGNORED_DIRS",
]
